#!/usr/bin/env python3
# pylint: disable=invalid-name  # filename uses hyphens per project convention
"""Push a TLS certificate to a Ubiquiti EdgeSwitch from Let's Encrypt or
private CA.

TL;DR: this script uploads a TLS certificate+key pair to a directory on a tftp
server, then connects to the EdgeSwitch via SSH VTY and runs commands to pull
and install the certificate(s)/key from the tftp server.

Ubiquiti EdgeSwitch (and probably many others) use a TLS certificate stored on
local NVRAM. However to programmatically upload a new certificate+key
generated by something like a private CA or Let's Encrypt, it can only populate
by fetching over tftp or http itself, it can't be uploaded directly nor is there
any sort of API.

Today this script only supports tftp but it should be somewhat easy to hack in
http support. Notably EdgeSwitch only supports tftp/http copy over IPv4 so this
can also be used to push certificates to a local dual-stack tftp server.

Requirements:
- run from a deploy script by acme.sh (e.g. wn_edgeswitch.sh) as the 'acme' user
(or whoever runs acme.sh)
- a tftp server
- SSH keys to log into host tftp server runs on
- Credentials for the EdgeSwitch stored with acme.sh or on a Hashicorp Vault
instance. (EdgeSwitches do not support any SSH keys)

This script does a number of things to smooth the process of keeping EdgeSwitch
certificates up to date as frequently as you want:

  1. Builds two PEM files with randomized filenames (so a normally-open tftp
     server doesn't hand them out to anyone who asks):
       - primary: the leaf certificate + private key, concatenated
       - chain:   the intermediate chain only (no leaf)
  2. scp's both to a staging directory on a tftp server, as the 'certs'
     user, using a dedicated SSH key readable by the 'acme' user.
  3. logs into the switch over SSH, enters enable mode, and runs the
     tftp-copy + "write memory" sequence to install them at
     nvram:sslpem-server / nvram:sslpem-root
  4. only once that succeeds, ssh's back to the tftp host and deletes the
     two staged files

Switch vty/enable credentials may be supplied directly, read from a local
per-switch file, or fetched from HashiCorp Vault (KV v2), in that order.
When none of --username/--password/--enable-password are given, the script
looks for a local creds file, and falls back to Vault only if that's also
missing. The 'vault' CLI is invoked using VAULT_ADDR from the environment
and a token read from ./switch-cert-installer-token. The secret path
defaults to:
  VAULT_SWITCH_PATH/<switch-host>
Override with --vault-path.

Local creds file format (JSON), default path
/opt/acme-sh/local/switch-creds/<switch-host>.json:
  {"username": "admin", "password": "...", "enable_password": "..."}

Examples:
    # acme.sh deploy hook invocation (creds come from the local file/Vault)
    ./edgeswitch-cert-deploy.py \\
        --switch-host switch01.example.com \\
        --key-file switch01.example.com.key \\
        --cert-file switch01.example.com.cer \\
        --ca-file switch01.example.com.ca \\
        --tftp-push-host tftp.example.com --tftp-fetch-host tftp.example.com

    # Explicit switch credentials, useful for a manual first test
    ./edgeswitch-cert-deploy.py \\
        --switch-host 192.168.21.1 \\
        --key-file switch.key --cert-file switch.cer --ca-file switch.ca \\
        --tftp-push-host tftp.example.com --tftp-fetch-host 192.168.21.8 \\
        --username admin --password swordfish --enable-password swordfish2
"""

import argparse
import json
import os
import re
import secrets
import shlex
import shutil
import socket
import subprocess
import sys
import tempfile
from dataclasses import dataclass

import paramiko  # pylint: disable=import-error

### Common customization settings ###

# If using Vault for switch credentials
VAULT_TOKEN_FILE = "./switch-cert-installer-token"
VAULT_SWITCH_PATH = "wannnet-infra/switches"

# If using local file for switch credentials
DEFAULT_CREDS_DIR = "/opt/acme-sh/local/switch-creds"

# acme.sh to TFTP server credentials
#
# SSH key (readable by acme user) to scp files to remote
# directory 'certs@host:/var/opt/tftpboot/certs'
DEFAULT_SSH_KEY = "/opt/pki/push/cert_push_acme"
DEFAULT_PUSH_USER = "certs"
DEFAULT_TFTP_DIR = "/var/opt/tftpboot/certs"
DEFAULT_TFTP_URL_PATH = "certs"

# Where the two staged PEMs are built before scp'ing to tftp server.
# This needs to be protected as it contains keys. It will need to be
# writable by 'acme' user yet permissions can be set to 644 or 444.
# e.g. directory 750 acme:certs
DEFAULT_WORK_DIR = "/opt/acme-sh/local"

### End of common customizations ###

SSH_CONNECT_TIMEOUT = 20
PROMPT_TIMEOUT = 15  # seconds to wait for a command/enable prompt
COPY_TIMEOUT = 60  # tftp copy + nvram write can take a while

# End-of-buffer patterns for the various things the switch CLI can be
# waiting on. All matched against the tail of the accumulated read buffer.
PROMPT_PAT = re.compile(r"[>#]\s*$")
ENABLE_PROMPT_PAT = re.compile(r"#\s*$")
PASSWORD_PROMPT_PAT = re.compile(r"(?i)password:?\s*$")
CONFIRM_PAT = re.compile(r"(?i)\(y/n\)\s*\??\s*$|continue\?\s*$|overwrite.*\?\s*$")
# Broad on purpose: errors messages don't necessarily carry a leading
# '%' marker ("Key not valid!") so this errs toward over-matching rather
# than missing real failure. Adjust as necessary.
ERROR_PAT = re.compile(
    r"(?i)\berror\b|\bnot valid\b|\binvalid\b|\bfail(ed|ure)?\b|"
    r"incomplete command|unauthorized|unable to|\bdenied\b"
)


class EdgeSwitchError(Exception):
    """Raised for anything that goes wrong talking to the switch, carrying
    the interactive transcript captured so far for troubleshooting."""


def die(msg):
    """Print an error message to stderr and exit with code 1."""
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def fetch_vault_credentials(vault_path):
    """Return (username, password, enable_password) from Vault KV v2."""
    vault_addr = os.environ.get("VAULT_ADDR", "").rstrip("/")
    if not vault_addr:
        die("VAULT_ADDR environment variable is not set")

    try:
        with open(VAULT_TOKEN_FILE, encoding="utf-8") as fh:
            token = fh.read().strip()
    except OSError as e:
        die(f"Cannot read Vault token from {VAULT_TOKEN_FILE}: {e}")

    env = {**os.environ, "VAULT_TOKEN": token, "VAULT_ADDR": vault_addr}
    try:
        result = subprocess.run(
            ["vault", "kv", "get", "-format=json", vault_path],
            env=env,
            capture_output=True,
            text=True,
            timeout=15,
            check=False,
        )
    except FileNotFoundError:
        die(
            "'vault' command not found — install the Vault CLI or provide "
            "--username/--password/--enable-password"
        )
    except subprocess.TimeoutExpired:
        die("vault command timed out")

    if result.returncode != 0:
        die(f"vault kv get failed: {result.stderr.strip()}")

    try:
        secret = json.loads(result.stdout)["data"]["data"]
        username = secret["username"]
        password = secret["password"]
        enable_password = secret["enable_password"]
    except (KeyError, json.JSONDecodeError) as e:
        die(f"Unexpected vault output parsing {vault_path!r}: {e}")

    print(f"Credentials fetched from Vault: {vault_path}")
    return username, password, enable_password


def load_local_credentials(path):
    """Return (username, password, enable_password) from a local JSON file."""
    try:
        with open(path, encoding="utf-8") as fh:
            secret = json.load(fh)
    except OSError as e:
        die(f"Cannot read local creds file {path}: {e}")
    except json.JSONDecodeError as e:
        die(f"Cannot parse local creds file {path}: {e}")

    try:
        username = secret["username"]
        password = secret["password"]
        enable_password = secret["enable_password"]
    except KeyError as e:
        die(f"Local creds file {path} is missing key {e}")

    print(f"Credentials loaded from local file: {path}")
    return username, password, enable_password


def resolve_credentials(args):
    """Resolve (username, password, enable_password) in priority order:
    CLI flags, then a local per-switch creds file, then Vault."""
    if args.username and args.password and args.enable_password:
        return args.username, args.password, args.enable_password

    creds_file = args.creds_file or os.path.join(
        DEFAULT_CREDS_DIR, f"{args.switch_host}.json"
    )
    if os.path.isfile(creds_file):
        return load_local_credentials(creds_file)

    vault_path = args.vault_path or f"{VAULT_SWITCH_PATH}/{args.switch_host}"
    return fetch_vault_credentials(vault_path)


# ---------------------------------------------------------------------------
# PEM staging + tftp-host scp/cleanup
# ---------------------------------------------------------------------------


def _write_random_pem(workdir, data):
    """Write data to a new 0644 file with a random name under workdir.

    Random names are used to prevent casual fishing of certs/keys while they're
    on the tftp/http server. Also when they're on the remote server they need
    to be world-readable. Create them here as mode 0644 and then we'll use
    `scp -p` to preserve the mode during upload.
    """
    name = secrets.token_hex(16) + ".pem"
    path = os.path.join(workdir, name)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
    with os.fdopen(fd, "wb") as fh:
        fh.write(data)
    return path, name


def build_pem_files(cert_file, key_file, ca_file, workdir):
    """Write the primary (cert+key) and chain (ca only) PEMs under randomly
    generated names in workdir. Returns ((path, name), (path, name))."""
    with open(cert_file, "rb") as fh:
        cert_data = fh.read()
    with open(key_file, "rb") as fh:
        key_data = fh.read()
    with open(ca_file, "rb") as fh:
        chain_data = fh.read()

    if not cert_data.endswith(b"\n"):
        cert_data += b"\n"

    primary = _write_random_pem(workdir, cert_data + key_data)
    chain = _write_random_pem(workdir, chain_data)
    return primary, chain


@dataclass
class PushTarget:
    """Where/how to scp the staged PEMs and clean them up afterward."""

    ssh_key: str
    push_user: str
    tftp_host: str
    tftp_dir: str


def _run_push_cmd(cmd, ssh_key, timeout, debug):
    """Run an scp/ssh command against the tftp push host.

    Deliberately not BatchMode=yes: by default, our ssh servers require
    publickey,keyboard-interactive for 2FA. BatchMode refuses to even
    attempt keyboard-interactive at all which annoyingly also causes it
    to skip using publickey.

    In debug mode, we add -v to ssh/scp to print ssh handshake debugging
    to show which keys it presents and other auth details. Can get noisy,
    but useful. Otherwise adds -q to suppress the scp progress meter and
    captures stderr.
    """
    if debug:
        print(f"DEBUG: {cmd[0]} using key {ssh_key}", file=sys.stderr)
        cmd = [cmd[0], "-v"] + cmd[1:]
        return subprocess.run(
            cmd, timeout=timeout, check=False, stdin=subprocess.DEVNULL
        )
    cmd = [cmd[0], "-q"] + cmd[1:]
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
        stdin=subprocess.DEVNULL,
    )


def scp_upload(local_paths, target, debug=False):
    """scp local_paths to target.push_user@target.tftp_host:target.tftp_dir/."""
    dest = f"{target.push_user}@{target.tftp_host}:{target.tftp_dir}/"
    cmd = [
        "scp",
        "-i",
        target.ssh_key,
        "-o",
        "StrictHostKeyChecking=no",
        "-p",
        *local_paths,
        dest,
    ]
    result = _run_push_cmd(cmd, target.ssh_key, 60, debug)
    if result.returncode != 0:
        detail = "" if debug else f": {(result.stderr or result.stdout).strip()}"
        die(f"scp to {dest} failed (key: {target.ssh_key}){detail}")


def ssh_remove(names, target, debug=False):
    """Best-effort: ssh in and rm the named files from target.tftp_dir."""
    remote_paths = " ".join(shlex.quote(f"{target.tftp_dir}/{n}") for n in names)
    cmd = [
        "ssh",
        "-i",
        target.ssh_key,
        "-o",
        "StrictHostKeyChecking=no",
        f"{target.push_user}@{target.tftp_host}",
        f"rm -f -- {remote_paths}",
    ]
    result = _run_push_cmd(cmd, target.ssh_key, 30, debug)
    if result.returncode != 0:
        detail = "" if debug else f": {(result.stderr or result.stdout).strip()}"
        print(
            f"WARNING: failed to clean up staged files on {target.tftp_host} "
            f"(key: {target.ssh_key}){detail}",
            file=sys.stderr,
        )


# ---------------------------------------------------------------------------
# Switch CLI interaction
# ---------------------------------------------------------------------------


def _read_until(chan, patterns, timeout, debug=False):
    """Read from an interactive channel until the tail of the accumulated
    buffer matches one of `patterns`, or `timeout` elapses. Returns the text
    read since the call started."""
    chan.settimeout(0.5)
    buf = ""
    deadline = timeout
    while deadline > 0:
        try:
            chunk = chan.recv(4096)
        except socket.timeout:
            deadline -= 0.5
            continue
        if not chunk:
            raise EdgeSwitchError(
                f"Connection closed unexpectedly. Output so far:\n{buf}"
            )
        text = chunk.decode("utf-8", errors="replace")
        buf += text
        if debug:
            sys.stderr.write(text)
        if any(pat.search(buf) for pat in patterns):
            return buf
    raise EdgeSwitchError(
        f"Timed out after {timeout}s waiting for a prompt. Output so far:\n{buf}"
    )


def send_command(chan, command, expect, timeout, debug=False):
    """Send `command`, wait for one of `expect` patterns, auto-confirming a
    single (y/n)-style prompt along the way. Raises EdgeSwitchError if the
    switch's own output looks like an error. Returns the captured output."""
    chan.send((command + "\n").encode())
    output = _read_until(chan, expect + [CONFIRM_PAT], timeout, debug)

    if CONFIRM_PAT.search(output) and not any(p.search(output) for p in expect):
        chan.send(b"y\n")
        output += _read_until(chan, expect, timeout, debug)

    if ERROR_PAT.search(output):
        raise EdgeSwitchError(f"Switch reported an error for {command!r}:\n{output}")
    return output


def run_deploy_sequence(
    switch_host,
    username,
    password,
    enable_password,
    tftp_ip,
    tftp_url_path,
    primary_name,
    chain_name,
    debug,
):  # pylint: disable=too-many-arguments,too-many-positional-arguments
    """Log into the switch and run the full enable/copy/write sequence.

    tftp_url_path is the directory the switch's own 'copy tftp://' command
    needs, relative to the tftp server's root -- NOT the filesystem staging
    path used for scp (--tftp-dir is an absolute path on the tftp host;
    this is the same directory expressed the way tftpd-hpa's chrooted root
    sees it, e.g. 'certs').
    """
    client = paramiko.SSHClient()
    # These are internal management-only switches with no maintained
    # known_hosts entry -- same posture as the ansible cisco_ios group_vars
    # (StrictHostKeyChecking=no).
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(
        switch_host,
        username=username,
        password=password,
        look_for_keys=False,
        allow_agent=False,
        timeout=SSH_CONNECT_TIMEOUT,
    )

    try:
        chan = client.invoke_shell()
        _read_until(chan, [PROMPT_PAT], PROMPT_TIMEOUT, debug)

        chan.send(b"enable\n")
        out = _read_until(
            chan, [PASSWORD_PROMPT_PAT, ENABLE_PROMPT_PAT], PROMPT_TIMEOUT, debug
        )
        if PASSWORD_PROMPT_PAT.search(out):
            chan.send((enable_password + "\n").encode())
            out = _read_until(chan, [PROMPT_PAT], PROMPT_TIMEOUT, debug)
        if not ENABLE_PROMPT_PAT.search(
            out.splitlines()[-1] if out.splitlines() else out
        ):
            raise EdgeSwitchError(f"Did not reach enable mode:\n{out}")

        url_path = tftp_url_path.strip("/")
        url_prefix = f"{tftp_ip}/{url_path}" if url_path else tftp_ip

        # This entire script just to run five commands on the switch!
        #
        # We have to disable HTTPS on the webUI while new certs are uploaded
        send_command(
            chan, "no ip http secure-server", [ENABLE_PROMPT_PAT], PROMPT_TIMEOUT, debug
        )
        send_command(
            chan,
            f"copy tftp://{url_prefix}/{primary_name} nvram:sslpem-server",
            [ENABLE_PROMPT_PAT],
            COPY_TIMEOUT,
            debug,
        )
        send_command(
            chan,
            f"copy tftp://{url_prefix}/{chain_name} nvram:sslpem-root",
            [ENABLE_PROMPT_PAT],
            COPY_TIMEOUT,
            debug,
        )
        send_command(
            chan, "ip http secure-server", [ENABLE_PROMPT_PAT], PROMPT_TIMEOUT, debug
        )
        send_command(chan, "write memory", [ENABLE_PROMPT_PAT], COPY_TIMEOUT, debug)
    finally:
        client.close()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main():  # pylint: disable=too-many-locals
    """Parse arguments and orchestrate the certificate deploy."""
    parser = argparse.ArgumentParser(
        description="Push a TLS certificate/key pair to a Ubiquiti EdgeSwitch via tftp",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--switch-host", required=True, help="Switch hostname or IP to ssh into"
    )
    parser.add_argument("--key-file", required=True, help="Private key file")
    parser.add_argument(
        "--cert-file", required=True, help="Leaf certificate file (no chain)"
    )
    parser.add_argument(
        "--ca-file", required=True, help="Intermediate chain file (no leaf)"
    )

    parser.add_argument(
        "--tftp-push-host",
        required=True,
        help="Host to scp the staged PEMs to (e.g. tftp-server.example.com)",
    )
    parser.add_argument(
        "--tftp-fetch-host",
        required=True,
        help="Hostname/address the switch itself uses in its 'copy tftp://' command"
        "(the switch may not be able to reach --tftp-push-host by the same name)",
    )
    parser.add_argument(
        "--tftp-dir", default=DEFAULT_TFTP_DIR, help="Staging dir on the tftp host"
    )
    parser.add_argument(
        "--tftp-url-path",
        default=DEFAULT_TFTP_URL_PATH,
        help="Directory the switch's 'copy tftp://' command uses, relative to the "
        "tftp server's root (not the same thing as --tftp-dir, which is an "
        "absolute filesystem path)",
    )
    parser.add_argument(
        "--ssh-key", default=DEFAULT_SSH_KEY, help="SSH key for the tftp host push"
    )
    parser.add_argument(
        "--push-user", default=DEFAULT_PUSH_USER, help="SSH user for the tftp host push"
    )
    parser.add_argument(
        "--work-dir",
        default=DEFAULT_WORK_DIR,
        help="Directory to build the staged PEMs under before scp (a fresh "
        "0700 subdirectory is created here per run and removed afterward)",
    )

    parser.add_argument("--username", default=None, help="Switch vty username")
    parser.add_argument("--password", default=None, help="Switch vty password")
    parser.add_argument(
        "--enable-password", default=None, help="Switch enable password"
    )
    parser.add_argument(
        "--creds-file",
        default=None,
        help=f"Local creds JSON file (default: {DEFAULT_CREDS_DIR}/<switch-host>.json)",
    )
    parser.add_argument(
        "--vault-path",
        default=None,
        help="Vault KV v2 path (default: VAULT_SWITCH_PATH/<switch-host>)",
    )

    parser.add_argument(
        "--keep-remote-files",
        action="store_true",
        help="Don't delete the staged PEMs from the tftp host after a "
        "successful deploy (debugging)",
    )
    parser.add_argument(
        "--quiet", action="store_true", help="Only print output on failure"
    )
    parser.add_argument(
        "--debug", action="store_true", help="Stream the raw switch CLI transcript"
    )
    args = parser.parse_args()

    for label, path in (
        ("--key-file", args.key_file),
        ("--cert-file", args.cert_file),
        ("--ca-file", args.ca_file),
    ):
        if not os.path.isfile(path):
            die(f"{label} '{path}' doesn't exist!")

    username, password, enable_password = resolve_credentials(args)
    push_target = PushTarget(
        args.ssh_key, args.push_user, args.tftp_push_host, args.tftp_dir
    )

    workdir = tempfile.mkdtemp(prefix="edgeswitch-cert-", dir=args.work_dir)
    try:
        (primary_path, primary_name), (chain_path, chain_name) = build_pem_files(
            args.cert_file, args.key_file, args.ca_file, workdir
        )

        if not args.quiet:
            print(
                f"Staging {primary_name}, {chain_name} on {args.tftp_push_host}:{args.tftp_dir} ..."
            )
        scp_upload([primary_path, chain_path], push_target, args.debug)
    finally:
        shutil.rmtree(workdir, ignore_errors=True)

    if not args.quiet:
        print(f"Deploying to {args.switch_host} ...")
    try:
        run_deploy_sequence(
            args.switch_host,
            username,
            password,
            enable_password,
            args.tftp_fetch_host,
            args.tftp_url_path,
            primary_name,
            chain_name,
            args.debug,
        )
    except (EdgeSwitchError, paramiko.SSHException, socket.error, OSError) as e:
        print(f"ERROR: deploy to {args.switch_host} failed: {e}", file=sys.stderr)
        print(
            f"Leaving {primary_name}, {chain_name} on "
            f"{args.tftp_push_host}:{args.tftp_dir} for troubleshooting.",
            file=sys.stderr,
        )
        sys.exit(1)

    if not args.keep_remote_files:
        ssh_remove([primary_name, chain_name], push_target, args.debug)

    if not args.quiet:
        print("All done!")


if __name__ == "__main__":
    main()
